"""
Spec: 20-plan/ecg-ppg-realworld/protocol-lock.md

Headline script — ecg-ppg-realworld.

Phases (selected via --phase):
  train     : train xresnet1d50 on dev split for `--epochs` (default 50)
              with early-stopping (patience 10 on dev-AF AUROC), saving
              best-AUROC weights per seed. Repeats for each --seed.
              Dev-only.
  calibrate : fit temperature T on dev calibration hold-out
              (20% of dev, seed=42 stratified) by Brier-min; fit
              abstention threshold on the remaining 80% of dev to
              achieve 17% abstention rate. Saves T + threshold per
              seed. Dev-only.
  test      : SINGLE-USE — apply T + threshold to held-out test split
              (record IDs from runs/partition.json["test_record_ids"]).
              Compute primary metric (PPV @ 17% abstention with bootstrap
              CI), baseline (PPV @ 0%), AUROC AF, ECE pre/post T,
              PPV-vs-coverage curve, McNemar test (PPV-flavoured) on the
              AF-predicted-positive subset, and multi-seed stability if
              multiple seeds are given. Touches held-out exactly once.
  all       : convenience: run train -> calibrate -> test for each seed.

Pre-run checklist (per protocol-lock §7) must be confirmed before
`test` will execute. The script writes a checklist log to
runs/pre-run-checklist.txt and refuses to run `test` unless the
checklist file exists with status "ALL_CHECKS_PASSED" (manual or
auto-generated by `--write-checklist`).

Outputs (all under 30-implement/ecg-ppg-realworld/runs/headline/):
  - weights_seed{seed}_epoch{n}.pt        (training checkpoints)
  - weights_seed{seed}_best.pt            (best by dev-AF AUROC)
  - train_seed{seed}_history.json         (per-epoch metrics)
  - calibration_seed{seed}.json           (T, threshold, dev metrics)
  - test_seed{seed}.json                  (held-out metrics; per seed)
  - headline_summary.json                 (cross-seed aggregate)
  - pre-run-checklist.txt
"""

from __future__ import annotations

import argparse
import json
import sys
import time
import traceback
from pathlib import Path

# Make 30-implement/shared importable.
_THIS = Path(__file__).resolve()
_REPO_ROOT = _THIS.parents[4]
_SHARED_PARENT = _REPO_ROOT / "30-implement"
if str(_SHARED_PARENT) not in sys.path:
    sys.path.insert(0, str(_SHARED_PARENT))


# ---------------------------------------------------------------------------
# Preprocessing + model — vendored from pilots P-2 / P-3 / P-4 to keep this
# file self-contained.
# ---------------------------------------------------------------------------

def preprocess(signal, fs: int):
    import numpy as np
    from scipy.signal import butter, filtfilt, iirnotch

    sos_b, sos_a = butter(4, 0.5 / (fs / 2), btype="highpass")
    signal = filtfilt(sos_b, sos_a, signal)
    notch_b, notch_a = iirnotch(50.0 / (fs / 2), Q=30)
    signal = filtfilt(notch_b, notch_a, signal)
    signal = np.clip(signal, -5.0, 5.0)
    mu = float(signal.mean())
    sigma = float(signal.std())
    if sigma > 1e-9:
        signal = (signal - mu) / sigma
    return signal


def find_reference_csv(cinc_dir: Path):
    for cand in (
        "REFERENCE-v3.csv",
        "REFERENCE.csv",
        "training2017/REFERENCE-v3.csv",
        "training2017/REFERENCE.csv",
    ):
        p = cinc_dir / cand
        if p.exists():
            return p
    return None


def build_xresnet1d50(in_channels: int = 1, n_out: int = 4):
    from fastai.vision.models.xresnet import ResBlock, XResNet

    return XResNet(
        ResBlock,
        expansion=4,
        layers=[3, 4, 6, 3],
        c_in=in_channels,
        n_out=n_out,
        ndim=1,
        ks=5,
    )


def pad_or_crop(signal, target_len: int):
    import numpy as np

    n = len(signal)
    if n == target_len:
        return signal.astype(np.float32)
    if n > target_len:
        start = (n - target_len) // 2
        return signal[start : start + target_len].astype(np.float32)
    out = np.zeros(target_len, dtype=np.float32)
    out[:n] = signal.astype(np.float32)
    return out


def load_record_signal(rec_path: Path, target_len: int, fs: int):
    import wfdb

    r = wfdb.rdrecord(str(rec_path))
    sig = r.p_signal[:, 0]
    sig = preprocess(sig, fs)
    sig = pad_or_crop(sig, target_len)
    return sig


LABEL_MAP = {"N": 0, "A": 1, "O": 2, "~": 3}
N_CLASSES = 4
AF_CLASS = 1


def in_memory_load(record_ids, labels, waveform_dir: Path, target_len: int, fs: int, log_every: int = 500):
    import numpy as np

    n = len(record_ids)
    X = np.zeros((n, target_len), dtype=np.float32)
    y = np.zeros(n, dtype=np.int64)
    n_failed = 0
    for i, (rid, lbl) in enumerate(zip(record_ids, labels)):
        try:
            X[i] = load_record_signal(waveform_dir / rid, target_len, fs)
        except Exception:  # noqa: BLE001
            n_failed += 1
        y[i] = LABEL_MAP[lbl]
        if (i + 1) % log_every == 0:
            print(f"  [load] {i+1}/{n} (failed={n_failed})", flush=True)
    return X, y, n_failed


# ---------------------------------------------------------------------------
# Phase: train
# ---------------------------------------------------------------------------

def class_weights_inv_freq(y, n_classes: int):
    import numpy as np

    counts = np.bincount(y, minlength=n_classes).astype(np.float32)
    total = counts.sum()
    # Avoid div-by-zero.
    counts = np.where(counts == 0, 1.0, counts)
    weights = total / (n_classes * counts)
    return weights


def af_auroc(y_true, probs):
    import numpy as np
    from sklearn.metrics import roc_auc_score

    y_bin = (np.asarray(y_true) == AF_CLASS).astype(np.int64)
    if y_bin.sum() == 0 or y_bin.sum() == len(y_bin):
        return float("nan")
    return float(roc_auc_score(y_bin, probs[:, AF_CLASS]))


def run_train(args):
    import numpy as np
    import pandas as pd
    import torch
    import torch.nn as nn
    from scipy.special import softmax
    from sklearn.model_selection import StratifiedShuffleSplit
    from torch.optim import Adam
    from torch.optim.lr_scheduler import CosineAnnealingLR

    cinc_dir = args.cinc_dir
    partition_json = args.partition_json
    runs_dir = args.runs_dir
    seed = args.seed

    if not cinc_dir.exists():
        return {"status": "fail", "reason": f"CinC 2017 dir not found at {cinc_dir}"}
    if not partition_json.exists():
        return {"status": "fail", "reason": f"partition.json not found at {partition_json}"}

    reference_csv = find_reference_csv(cinc_dir)
    if reference_csv is None:
        return {"status": "fail", "reason": f"REFERENCE csv not found under {cinc_dir}"}
    if not torch.cuda.is_available():
        return {"status": "fail", "reason": "torch.cuda unavailable"}

    waveform_dir = reference_csv.parent
    df = pd.read_csv(reference_csv, header=None, names=["record_id", "label"])
    partition = json.loads(partition_json.read_text())
    dev_ids = set(partition["dev_record_ids"])
    df_dev = df[df["record_id"].isin(dev_ids)].copy()
    # Spec excludes noisy '~' from training (carried through from P-2 / P-4).
    df_dev = df_dev[df_dev["label"] != "~"].reset_index(drop=True)

    # Internal dev split: 20% calibration hold-out (used in `calibrate`
    # phase), 80% training. Same seed/stratification as P-4 to keep the
    # training set stable across phases.
    sss = StratifiedShuffleSplit(n_splits=1, test_size=0.20, random_state=42)
    train_idx, cal_holdout_idx = next(sss.split(df_dev["record_id"].values, df_dev["label"].values))
    df_train = df_dev.iloc[train_idx].reset_index(drop=True)
    df_cal_holdout = df_dev.iloc[cal_holdout_idx].reset_index(drop=True)

    print(f"[headline-train] seed={seed} train={len(df_train)} cal_holdout={len(df_cal_holdout)}", flush=True)

    print("[headline-train] loading + preprocessing waveforms...", flush=True)
    t0 = time.perf_counter()
    X_train, y_train, n_failed_train = in_memory_load(
        df_train["record_id"].values, df_train["label"].values, waveform_dir, args.target_len, args.fs
    )
    X_cal, y_cal, n_failed_cal = in_memory_load(
        df_cal_holdout["record_id"].values, df_cal_holdout["label"].values, waveform_dir, args.target_len, args.fs
    )
    load_elapsed = time.perf_counter() - t0
    print(f"[headline-train] load complete in {load_elapsed:.1f}s (train_failed={n_failed_train}, cal_failed={n_failed_cal})", flush=True)

    cw = class_weights_inv_freq(y_train, N_CLASSES)
    print(f"[headline-train] class weights (inv-freq): {cw.tolist()}", flush=True)

    # Reproducibility
    torch.manual_seed(seed)
    np.random.seed(seed)
    rng = np.random.default_rng(seed)

    device = "cuda:0"
    model = build_xresnet1d50(in_channels=1, n_out=N_CLASSES).to(device)
    weight_tensor = torch.tensor(cw, dtype=torch.float32, device=device)
    criterion = nn.CrossEntropyLoss(weight=weight_tensor)
    optimizer = Adam(model.parameters(), lr=args.lr)
    scheduler = CosineAnnealingLR(optimizer, T_max=args.epochs)

    out_dir = runs_dir / "headline"
    out_dir.mkdir(parents=True, exist_ok=True)
    history = []
    best_auc = -1.0
    best_path = out_dir / f"weights_seed{seed}_best.pt"
    epochs_since_best = 0
    early_stop_triggered = False

    n_train = len(X_train)
    train_idx_arr = np.arange(n_train)
    for epoch in range(1, args.epochs + 1):
        model.train()
        rng.shuffle(train_idx_arr)
        running = 0.0
        n_seen = 0
        ep_t0 = time.perf_counter()
        for s in range(0, n_train, args.batch_size):
            batch_idx = train_idx_arr[s : s + args.batch_size]
            xb = torch.from_numpy(X_train[batch_idx]).unsqueeze(1).to(device, non_blocking=True)
            yb = torch.from_numpy(y_train[batch_idx]).to(device, non_blocking=True)
            optimizer.zero_grad(set_to_none=True)
            logits = model(xb)
            loss = criterion(logits, yb)
            loss.backward()
            optimizer.step()
            running += float(loss.item()) * len(batch_idx)
            n_seen += len(batch_idx)
            if (s // args.batch_size) % 100 == 99:
                print(f"  [seed={seed} ep {epoch}/{args.epochs}] step {s//args.batch_size+1}/{(n_train+args.batch_size-1)//args.batch_size} running_loss={running/n_seen:.4f} elapsed={time.perf_counter()-ep_t0:.0f}s", flush=True)
        scheduler.step()
        train_loss = running / max(n_seen, 1)

        # Eval on calibration hold-out for early stopping monitor.
        model.eval()
        cal_logits = []
        with torch.no_grad():
            for s in range(0, len(X_cal), args.batch_size):
                xb = torch.from_numpy(X_cal[s : s + args.batch_size]).unsqueeze(1).to(device)
                cal_logits.append(model(xb).cpu().numpy())
        cal_logits = np.concatenate(cal_logits, axis=0)
        cal_probs = softmax(cal_logits, axis=1)
        cal_auc = af_auroc(y_cal, cal_probs)

        ep_elapsed = time.perf_counter() - ep_t0
        record = {"epoch": epoch, "train_loss": round(train_loss, 5), "cal_holdout_af_auroc": round(cal_auc, 5), "elapsed_s": round(ep_elapsed, 1), "lr": float(scheduler.get_last_lr()[0])}
        history.append(record)
        print(f"[seed={seed}] epoch {epoch}: train_loss={train_loss:.4f} cal_af_auroc={cal_auc:.4f} ({ep_elapsed:.0f}s)", flush=True)

        # Per-epoch checkpoint (overwrite — no need to keep all).
        torch.save(model.state_dict(), out_dir / f"weights_seed{seed}_last.pt")
        # Early-stopping bookkeeping.
        if cal_auc > best_auc:
            best_auc = cal_auc
            epochs_since_best = 0
            torch.save(model.state_dict(), best_path)
            print(f"  -> new best @ epoch {epoch}: AUROC={best_auc:.4f}", flush=True)
        else:
            epochs_since_best += 1
            if epochs_since_best >= args.early_stop_patience:
                early_stop_triggered = True
                print(f"  -> early stop at epoch {epoch} (no improvement in {args.early_stop_patience} epochs; best={best_auc:.4f})", flush=True)
                break

    history_path = out_dir / f"train_seed{seed}_history.json"
    history_path.write_text(json.dumps({
        "seed": seed,
        "epochs_run": len(history),
        "epochs_planned": args.epochs,
        "early_stop_triggered": early_stop_triggered,
        "best_cal_holdout_af_auroc": round(best_auc, 5),
        "history": history,
        "best_weights": str(best_path),
    }, indent=2))
    print(f"[headline-train] seed={seed} done. best AUROC={best_auc:.4f}. History: {history_path}", flush=True)
    return {"status": "pass", "seed": seed, "best_auroc": round(best_auc, 5), "epochs_run": len(history), "best_weights_path": str(best_path)}


# ---------------------------------------------------------------------------
# Phase: calibrate
# ---------------------------------------------------------------------------

def fit_temperature_brier(logits, y_true, n_classes: int):
    import numpy as np
    from scipy.optimize import minimize_scalar
    from scipy.special import softmax

    y_onehot = np.zeros((len(y_true), n_classes), dtype=np.float32)
    y_onehot[np.arange(len(y_true)), y_true] = 1.0

    def brier(T):
        probs = softmax(logits / max(T, 1e-3), axis=1)
        return float(((probs - y_onehot) ** 2).sum(axis=1).mean())

    res = minimize_scalar(brier, bounds=(0.5, 10.0), method="bounded", options={"xatol": 1e-3})
    T = float(res.x)
    return T, brier(1.0), brier(T)


def run_calibrate(args):
    """Two stages, dev only:
       (i)  fit T on the cal-holdout subset (20% of dev, the same one
            the training run held out for early-stopping monitoring).
       (ii) evaluate on the *training* portion (80% of dev) and pick the
            confidence threshold that achieves --target-abstention rate.

       Note: stage (ii) uses the SAME training data the model has seen.
       Per protocol-lock §4: "Threshold tuned on the remaining 80 % of
       dev split to achieve 17 % abstention rate." That split is the
       training portion here (5,279 records). Using the model's training
       data to fit an *abstention threshold* (not a model parameter)
       is a deliberate spec choice: it ensures the threshold corresponds
       to a 17% abstention rate on the inputs the model is most
       confident on, which is the conservative reading of the BASEL 17%
       inconclusive-rate budget. The held-out test split is untouched.
    """
    import numpy as np
    import pandas as pd
    import torch
    from scipy.special import softmax
    from sklearn.model_selection import StratifiedShuffleSplit

    cinc_dir = args.cinc_dir
    partition_json = args.partition_json
    runs_dir = args.runs_dir
    seed = args.seed

    if not torch.cuda.is_available():
        return {"status": "fail", "reason": "torch.cuda unavailable"}
    out_dir = runs_dir / "headline"
    weights_path = out_dir / f"weights_seed{seed}_best.pt"
    if not weights_path.exists():
        return {"status": "fail", "reason": f"weights not found: {weights_path} (run --phase=train first)"}

    reference_csv = find_reference_csv(cinc_dir)
    waveform_dir = reference_csv.parent
    df = pd.read_csv(reference_csv, header=None, names=["record_id", "label"])
    partition = json.loads(partition_json.read_text())
    dev_ids = set(partition["dev_record_ids"])
    df_dev = df[df["record_id"].isin(dev_ids)].copy()
    df_dev = df_dev[df_dev["label"] != "~"].reset_index(drop=True)
    sss = StratifiedShuffleSplit(n_splits=1, test_size=0.20, random_state=42)
    train_idx, cal_idx = next(sss.split(df_dev["record_id"].values, df_dev["label"].values))
    df_train = df_dev.iloc[train_idx].reset_index(drop=True)
    df_cal = df_dev.iloc[cal_idx].reset_index(drop=True)

    print(f"[calibrate] seed={seed} dev_train={len(df_train)} cal_holdout={len(df_cal)}", flush=True)

    print("[calibrate] loading dev waveforms (cal hold-out + train)...", flush=True)
    t0 = time.perf_counter()
    X_cal, y_cal, _ = in_memory_load(df_cal["record_id"].values, df_cal["label"].values, waveform_dir, args.target_len, args.fs)
    X_train, y_train, _ = in_memory_load(df_train["record_id"].values, df_train["label"].values, waveform_dir, args.target_len, args.fs)
    print(f"[calibrate] load done in {time.perf_counter()-t0:.1f}s", flush=True)

    device = "cuda:0"
    model = build_xresnet1d50(in_channels=1, n_out=N_CLASSES).to(device)
    state = torch.load(str(weights_path), map_location=device, weights_only=False)
    if isinstance(state, dict) and "state_dict" in state:
        model.load_state_dict(state["state_dict"])
    else:
        model.load_state_dict(state)
    model.eval()

    def collect_logits(X):
        out = []
        with torch.no_grad():
            for s in range(0, len(X), args.batch_size):
                xb = torch.from_numpy(X[s : s + args.batch_size]).unsqueeze(1).to(device)
                out.append(model(xb).cpu().numpy())
        return np.concatenate(out, axis=0)

    cal_logits = collect_logits(X_cal)
    train_logits = collect_logits(X_train)

    # (i) Fit T on cal-holdout.
    T, brier_pre, brier_post = fit_temperature_brier(cal_logits, y_cal, N_CLASSES)
    cal_probs_post = softmax(cal_logits / max(T, 1e-3), axis=1)
    train_probs_post = softmax(train_logits / max(T, 1e-3), axis=1)
    cal_auroc_af = af_auroc(y_cal, cal_probs_post)

    # (ii) Pick threshold on dev-train so that fraction-below-threshold == target abstention
    target = args.target_abstention
    train_max_conf = train_probs_post.max(axis=1)
    threshold = float(np.quantile(train_max_conf, target))
    achieved = float(np.mean(train_max_conf < threshold))

    artifact = {
        "seed": seed,
        "T": round(T, 5),
        "T_search_bounds": [0.5, 10.0],
        "brier_uncalibrated_on_cal": round(brier_pre, 5),
        "brier_calibrated_on_cal": round(brier_post, 5),
        "calibration_auroc_af_post_T_on_cal": round(cal_auroc_af, 5),
        "abstention_threshold": round(threshold, 6),
        "abstention_threshold_target_rate": target,
        "abstention_threshold_achieved_rate_on_dev_train": round(achieved, 5),
        "n_cal_holdout": int(len(y_cal)),
        "n_dev_train": int(len(y_train)),
        "weights_path": str(weights_path),
    }
    out_path = out_dir / f"calibration_seed{seed}.json"
    out_path.write_text(json.dumps(artifact, indent=2))
    print(json.dumps(artifact, indent=2))
    print(f"\nWrote {out_path}", flush=True)
    return {"status": "pass", **artifact}


# ---------------------------------------------------------------------------
# Phase: pre-run-checklist + test (held-out single touch)
# ---------------------------------------------------------------------------

def write_checklist(args, runs_dir: Path) -> dict:
    """Auto-generate the pre-run-checklist by inspecting expected artifacts.
    Each item is checked against the filesystem; if any item fails, the
    checklist file is still written (with FAIL markers) but `test` will
    refuse to run. Caller can hand-edit + flip to ALL_CHECKS_PASSED only
    if the auto-check is wrong (which would itself be a bug to fix).
    """
    out_dir = runs_dir / "headline"
    seeds = args.seeds
    checks = []

    # 1. Per-seed weights present.
    for s in seeds:
        p = out_dir / f"weights_seed{s}_best.pt"
        checks.append(("weights_seed%s_best.pt" % s, p.exists()))

    # 2. T fitted + saved per seed.
    for s in seeds:
        p = out_dir / f"calibration_seed{s}.json"
        checks.append(("calibration_seed%s.json" % s, p.exists()))

    # 3. Threshold present (same JSON as #2; double-check abstention_threshold key).
    for s in seeds:
        p = out_dir / f"calibration_seed{s}.json"
        if p.exists():
            try:
                d = json.loads(p.read_text())
                checks.append(("calibration_seed%s.json has abstention_threshold" % s, "abstention_threshold" in d))
            except Exception:  # noqa: BLE001
                checks.append(("calibration_seed%s.json parseable" % s, False))
        else:
            checks.append(("calibration_seed%s.json has abstention_threshold" % s, False))

    # 4. Partition audit.
    partition_audit = (runs_dir / "partition_audit.txt")
    checks.append(("partition_audit.txt exists", partition_audit.exists()))

    # 5. Test split untouched -- we cannot prove this from disk alone;
    # check that no earlier `test_seed*.json` exists.
    for s in seeds:
        p = out_dir / f"test_seed{s}.json"
        checks.append(("test_seed%s.json absent (not yet touched)" % s, not p.exists()))

    # 6. Seeds documented.
    checks.append(("seeds documented", len(seeds) > 0))
    checks.append(("batch_size documented", args.batch_size > 0))
    checks.append(("model variant documented", args.model in ("xresnet1d50", "xresnet1d18")))

    all_pass = all(ok for _, ok in checks)
    out = runs_dir / "pre-run-checklist.txt"
    lines = [
        "# Pre-run checklist — ecg-ppg-realworld headline",
        f"# Generated: {time.strftime('%Y-%m-%d %H:%M:%S')}",
        f"# Seeds: {seeds}",
        f"# Model: {args.model}",
        f"# Batch size: {args.batch_size}",
        "",
    ]
    for name, ok in checks:
        lines.append(f"[{'X' if ok else ' '}] {name}")
    lines.append("")
    lines.append("STATUS: ALL_CHECKS_PASSED" if all_pass else "STATUS: FAIL")
    out.write_text("\n".join(lines))
    print("\n".join(lines))
    return {"status": "pass" if all_pass else "fail", "checklist_path": str(out)}


def bootstrap_ppv_ci(y_true_bin, y_pred_bin, mask_committed, n_boot: int, seed: int):
    """Stratified-by-y_true bootstrap of PPV on the predicted-positive
    subset within the committed subset. Returns (point, lo, hi)."""
    import numpy as np

    rng = np.random.default_rng(seed)
    y_true_bin = np.asarray(y_true_bin)
    y_pred_bin = np.asarray(y_pred_bin)
    mask_committed = np.asarray(mask_committed).astype(bool)

    pos_idx = np.where(y_true_bin == 1)[0]
    neg_idx = np.where(y_true_bin == 0)[0]

    def _ppv(idx_pool):
        m = mask_committed[idx_pool]
        if m.sum() == 0:
            return float("nan")
        idx_committed = idx_pool[m]
        pp = y_pred_bin[idx_committed] == 1
        if pp.sum() == 0:
            return float("nan")
        return float((y_true_bin[idx_committed][pp] == 1).sum() / pp.sum())

    boots = []
    for _ in range(n_boot):
        s_pos = rng.choice(pos_idx, size=len(pos_idx), replace=True)
        s_neg = rng.choice(neg_idx, size=len(neg_idx), replace=True)
        s_all = np.concatenate([s_pos, s_neg])
        boots.append(_ppv(s_all))
    boots = np.asarray([b for b in boots if not (b != b)], dtype=np.float64)
    point = _ppv(np.arange(len(y_true_bin)))
    if len(boots) == 0:
        return point, float("nan"), float("nan")
    lo = float(np.quantile(boots, 0.025))
    hi = float(np.quantile(boots, 0.975))
    return point, lo, hi


def compute_ece(probs, y_true, n_bins: int = 15) -> float:
    import numpy as np

    pred = probs.argmax(axis=1)
    conf = probs.max(axis=1)
    correct = (pred == y_true).astype(float)
    bins = np.linspace(0.0, 1.0, n_bins + 1)
    ece = 0.0
    n = len(y_true)
    for i in range(n_bins):
        lo, hi = bins[i], bins[i + 1]
        if i == n_bins - 1:
            mask = (conf >= lo) & (conf <= hi)
        else:
            mask = (conf >= lo) & (conf < hi)
        if mask.sum() == 0:
            continue
        acc = float(correct[mask].mean())
        c = float(conf[mask].mean())
        ece += (mask.sum() / n) * abs(acc - c)
    return float(ece)


def run_test(args):
    """Single authorized touch of the held-out partition.

    Refuses to proceed unless `runs/pre-run-checklist.txt` ends in
    `STATUS: ALL_CHECKS_PASSED`. Caller must run --phase=write-checklist
    first.
    """
    import numpy as np
    import pandas as pd
    import torch
    from scipy.special import softmax
    from sklearn.metrics import roc_auc_score
    from statsmodels.stats.contingency_tables import mcnemar

    from shared.eval import ppv_at_coverage, selective_classification_curve

    cinc_dir = args.cinc_dir
    partition_json = args.partition_json
    runs_dir = args.runs_dir
    seed = args.seed
    out_dir = runs_dir / "headline"
    weights_path = out_dir / f"weights_seed{seed}_best.pt"
    cal_path = out_dir / f"calibration_seed{seed}.json"
    test_out_path = out_dir / f"test_seed{seed}.json"

    # Idempotency guard: if test_seed{seed}.json already exists, refuse
    # to overwrite. Held-out is touched once.
    if test_out_path.exists():
        return {"status": "fail", "reason": f"test_seed{seed}.json already exists. Held-out has already been touched for this seed. Move/rename the existing file if a re-run is genuinely necessary (and document why)."}

    checklist = runs_dir / "pre-run-checklist.txt"
    if not checklist.exists():
        return {"status": "fail", "reason": f"checklist missing at {checklist}. Run --phase=write-checklist first."}
    if "ALL_CHECKS_PASSED" not in checklist.read_text():
        return {"status": "fail", "reason": "checklist STATUS != ALL_CHECKS_PASSED"}

    if not weights_path.exists():
        return {"status": "fail", "reason": f"weights not found: {weights_path}"}
    if not cal_path.exists():
        return {"status": "fail", "reason": f"calibration not found: {cal_path}"}
    cal_meta = json.loads(cal_path.read_text())
    T = float(cal_meta["T"])
    threshold = float(cal_meta["abstention_threshold"])

    if not torch.cuda.is_available():
        return {"status": "fail", "reason": "torch.cuda unavailable"}

    reference_csv = find_reference_csv(cinc_dir)
    waveform_dir = reference_csv.parent
    df = pd.read_csv(reference_csv, header=None, names=["record_id", "label"])
    partition = json.loads(partition_json.read_text())
    test_ids = set(partition["test_record_ids"])
    df_test = df[df["record_id"].isin(test_ids)].copy()
    # Spec §2: 46 noisy '~' excluded throughout (training + evaluation).
    # Per partition_audit they should not appear in test_record_ids since
    # the working set excludes noisy. But filter defensively in case.
    n_pre = len(df_test)
    df_test = df_test[df_test["label"] != "~"].reset_index(drop=True)
    n_excluded_noisy = n_pre - len(df_test)

    print(f"[test] HELD-OUT TOUCH: seed={seed} test_records={len(df_test)} (excluded_noisy={n_excluded_noisy}) T={T:.4f} threshold={threshold:.4f}", flush=True)

    print("[test] loading test waveforms...", flush=True)
    t0 = time.perf_counter()
    X_test, y_test, n_failed = in_memory_load(df_test["record_id"].values, df_test["label"].values, waveform_dir, args.target_len, args.fs)
    print(f"[test] load done in {time.perf_counter()-t0:.1f}s (failed={n_failed})", flush=True)

    device = "cuda:0"
    model = build_xresnet1d50(in_channels=1, n_out=N_CLASSES).to(device)
    state = torch.load(str(weights_path), map_location=device, weights_only=False)
    if isinstance(state, dict) and "state_dict" in state:
        model.load_state_dict(state["state_dict"])
    else:
        model.load_state_dict(state)
    model.eval()

    print("[test] inference...", flush=True)
    logits = []
    with torch.no_grad():
        for s in range(0, len(X_test), args.batch_size):
            xb = torch.from_numpy(X_test[s : s + args.batch_size]).unsqueeze(1).to(device)
            logits.append(model(xb).cpu().numpy())
    logits = np.concatenate(logits, axis=0)
    probs_uncal = softmax(logits, axis=1)
    probs_cal = softmax(logits / max(T, 1e-3), axis=1)

    pred = probs_cal.argmax(axis=1)
    conf = probs_cal.max(axis=1)
    committed = conf >= threshold
    achieved_abstention = float(1.0 - committed.mean())

    # AUROC AF.
    y_bin = (y_test == AF_CLASS).astype(np.int64)
    auroc_af = float(roc_auc_score(y_bin, probs_cal[:, AF_CLASS])) if y_bin.sum() > 0 else float("nan")

    # ECE pre/post T (overall).
    ece_uncal = compute_ece(probs_uncal, y_test, n_bins=15)
    ece_cal = compute_ece(probs_cal, y_test, n_bins=15)

    # PPV at 17% (committed subset, AF-vs-rest).
    pred_bin = (pred == AF_CLASS).astype(np.int64)
    ppv_17_point, ppv_17_lo, ppv_17_hi = bootstrap_ppv_ci(y_bin, pred_bin, committed, n_boot=args.n_boot, seed=42)
    n_committed = int(committed.sum())

    # Baseline PPV at 0% abstention.
    all_in = np.ones_like(committed, dtype=bool)
    ppv_0_point, ppv_0_lo, ppv_0_hi = bootstrap_ppv_ci(y_bin, pred_bin, all_in, n_boot=args.n_boot, seed=42)

    # PPV-vs-coverage curve at 6 protocol-locked points.
    coverages = [1.00, 0.95, 0.90, 0.85, 0.83, 0.79]
    sc = selective_classification_curve(
        confidences=conf,
        correct=(pred == y_test).astype(np.int64),
        coverages=coverages,
    )
    ppv_curve = ppv_at_coverage(
        y_true=y_bin,
        y_pred=pred_bin,
        confidences=conf,
        coverages=coverages,
        bootstrap_n=args.n_boot,
        bootstrap_seed=42,
    )

    # McNemar (PPV-flavoured): on AF-predicted-positive subset under
    # both conditions. The "no-abstention" condition commits on every
    # input (mask = all-True). The "abstention" condition uses the
    # threshold mask. We compare TP/FP labels for AF-predicted records
    # that survive in BOTH conditions.
    af_pred_idx = np.where(pred_bin == 1)[0]
    # Both conditions must commit. With threshold-based abstention,
    # the abstention condition drops some AF-predicted records (those
    # with conf < threshold). Define the comparison universe as the
    # union of AF-predicted records under either condition; then label
    # each as TP/FP per condition (records dropped by abstention are
    # excluded from the abstention column entirely).
    table = np.array([
        # Rows: no-abstain TP / FP. Columns: abstention TP / FP / dropped.
        # Standard McNemar 2x2: discordant cells only matter.
        # We construct a 2x2 by counting:
        #   a = both TP (concordant TP)
        #   b = no-abstain TP, abstention drops or FP
        #   c = no-abstain FP, abstention TP
        #   d = both FP / both dropped (concordant)
        [0, 0],
        [0, 0],
    ], dtype=np.int64)
    for i in af_pred_idx:
        no_abs_tp = (y_bin[i] == 1)
        if not committed[i]:
            # abstention dropped this AF-predicted record entirely.
            # In a PPV-comparing 2x2, dropping an FP is good for PPV,
            # dropping a TP is bad for PPV. Treat drops as the
            # "discordant" cells:
            #   no-abstain TP, abstention drops (loss of TP) -> b cell
            #   no-abstain FP, abstention drops (gain for PPV) -> c cell
            if no_abs_tp:
                table[0, 1] += 1  # b
            else:
                table[1, 0] += 1  # c
        else:
            abs_tp = (y_bin[i] == 1)
            if no_abs_tp and abs_tp:
                table[0, 0] += 1  # a
            elif (not no_abs_tp) and (not abs_tp):
                table[1, 1] += 1  # d
            elif no_abs_tp and not abs_tp:
                table[0, 1] += 1  # discordant TP->FP: b
            else:
                table[1, 0] += 1  # discordant FP->TP: c
    # statsmodels McNemar uses table where off-diagonals are b and c.
    try:
        m_res = mcnemar(table, exact=False, correction=True)
        mcnemar_p = float(m_res.pvalue)
        mcnemar_stat = float(m_res.statistic)
    except Exception as e:  # noqa: BLE001
        mcnemar_p = float("nan")
        mcnemar_stat = float("nan")
        print(f"[test] McNemar fallback: {e}", flush=True)

    ppv_improvement_pp = (ppv_17_point - ppv_0_point) * 100.0

    # Verdict per protocol-lock §6 / §7.
    if (mcnemar_p < 0.05) and (ppv_improvement_pp >= 5.0):
        verdict = "POSITIVE: statistically significant and clinically meaningful PPV improvement from calibrated abstention"
    elif (mcnemar_p < 0.05) and (ppv_improvement_pp < 5.0):
        verdict = "POSITIVE-SMALL: statistically significant but small PPV improvement"
    elif (mcnemar_p >= 0.05) and (ppv_17_hi - ppv_0_point) * 100.0 < 10.0:
        verdict = "NULL: no statistically significant PPV improvement; CI rules out 10pp+"
    elif mcnemar_p >= 0.05:
        verdict = "INCONCLUSIVE: no significance and CI too wide to rule out a meaningful effect"
    else:
        verdict = "UNCATEGORISED"

    result = {
        "status": "pass",
        "seed": seed,
        "T": round(T, 5),
        "abstention_threshold": round(threshold, 6),
        "abstention_threshold_target": cal_meta["abstention_threshold_target_rate"],
        "abstention_rate_achieved_on_test": round(achieved_abstention, 5),
        "n_test": int(len(y_test)),
        "n_excluded_noisy": int(n_excluded_noisy),
        "n_committed": n_committed,
        "auroc_af_post_T": round(auroc_af, 5),
        "ece_uncal": round(ece_uncal, 5),
        "ece_cal": round(ece_cal, 5),
        "ppv_at_17_abstention": {
            "point": round(ppv_17_point, 5),
            "ci95_lo": round(ppv_17_lo, 5),
            "ci95_hi": round(ppv_17_hi, 5),
            "n_committed": n_committed,
        },
        "ppv_at_0_abstention_baseline": {
            "point": round(ppv_0_point, 5),
            "ci95_lo": round(ppv_0_lo, 5),
            "ci95_hi": round(ppv_0_hi, 5),
            "n_committed": int(len(y_test)),
        },
        "ppv_improvement_pp": round(ppv_improvement_pp, 3),
        "mcnemar_table_2x2": table.tolist(),
        "mcnemar_statistic": round(mcnemar_stat, 5),
        "mcnemar_p_value": round(mcnemar_p, 5),
        "ppv_vs_coverage_curve": ppv_curve,
        "selective_classification_curve": sc,
        "bootstrap_n": args.n_boot,
        "bootstrap_seed": 42,
        "weights_path": str(weights_path),
        "verdict": verdict,
        "spec": "20-plan/ecg-ppg-realworld/protocol-lock.md §5-§7",
    }
    test_out_path.write_text(json.dumps(result, indent=2))
    print(json.dumps({k: v for k, v in result.items() if k not in ("ppv_vs_coverage_curve", "selective_classification_curve")}, indent=2))
    print(f"\nWrote {test_out_path}", flush=True)
    return result


# ---------------------------------------------------------------------------
# Phase: aggregate (multi-seed cross-summary; touches no held-out anew)
# ---------------------------------------------------------------------------

def run_aggregate(args):
    import numpy as np

    out_dir = args.runs_dir / "headline"
    seed_results = []
    for s in args.seeds:
        p = out_dir / f"test_seed{s}.json"
        if p.exists():
            seed_results.append(json.loads(p.read_text()))
    if not seed_results:
        return {"status": "fail", "reason": "no test_seed*.json found yet"}

    def _val(key, sub=None):
        out = []
        for r in seed_results:
            v = r[key] if sub is None else r[key][sub]
            out.append(v)
        return np.asarray(out, dtype=float)

    summary = {
        "n_seeds_aggregated": len(seed_results),
        "seeds": [r["seed"] for r in seed_results],
        "ppv_at_17_abstention_mean": float(_val("ppv_at_17_abstention", "point").mean()),
        "ppv_at_17_abstention_std": float(_val("ppv_at_17_abstention", "point").std(ddof=1) if len(seed_results) > 1 else 0.0),
        "ppv_baseline_mean": float(_val("ppv_at_0_abstention_baseline", "point").mean()),
        "ppv_baseline_std": float(_val("ppv_at_0_abstention_baseline", "point").std(ddof=1) if len(seed_results) > 1 else 0.0),
        "auroc_af_mean": float(_val("auroc_af_post_T").mean()),
        "auroc_af_std": float(_val("auroc_af_post_T").std(ddof=1) if len(seed_results) > 1 else 0.0),
        "abstention_rate_achieved_mean": float(_val("abstention_rate_achieved_on_test").mean()),
        "ece_cal_mean": float(_val("ece_cal").mean()),
        "primary_seed": 42,
        "primary_seed_result": next((r for r in seed_results if r["seed"] == 42), None),
    }
    out_path = out_dir / "headline_summary.json"
    out_path.write_text(json.dumps(summary, indent=2))
    print(json.dumps({k: v for k, v in summary.items() if k != "primary_seed_result"}, indent=2))
    print(f"\nWrote {out_path}")
    return {"status": "pass", **{k: v for k, v in summary.items() if k != "primary_seed_result"}}


# ---------------------------------------------------------------------------

def main() -> int:
    ap = argparse.ArgumentParser(description="ecg-ppg-realworld headline runner")
    ap.add_argument("--phase", required=True, choices=("train", "calibrate", "test", "write-checklist", "aggregate"))
    ap.add_argument("--cinc-dir", type=Path, default=Path.home() / "physionet_data" / "challenge-2017-1.0.0")
    ap.add_argument("--partition-json", type=Path, default=Path(__file__).resolve().parents[2] / "runs" / "partition.json")
    ap.add_argument("--runs-dir", type=Path, default=Path(__file__).resolve().parents[2] / "runs")
    ap.add_argument("--seed", type=int, default=42)
    ap.add_argument("--seeds", type=int, nargs="*", default=[42, 1337, 2025])
    ap.add_argument("--target-len", type=int, default=9000)
    ap.add_argument("--fs", type=int, default=300)
    ap.add_argument("--epochs", type=int, default=50)
    ap.add_argument("--early-stop-patience", type=int, default=10)
    ap.add_argument("--batch-size", type=int, default=8)
    ap.add_argument("--lr", type=float, default=1e-3)
    ap.add_argument("--target-abstention", type=float, default=0.17)
    ap.add_argument("--n-boot", type=int, default=2000)
    ap.add_argument("--model", default="xresnet1d50", choices=("xresnet1d50", "xresnet1d18"))
    args = ap.parse_args()

    args.runs_dir.mkdir(parents=True, exist_ok=True)
    (args.runs_dir / "headline").mkdir(parents=True, exist_ok=True)

    try:
        if args.phase == "train":
            result = run_train(args)
        elif args.phase == "calibrate":
            result = run_calibrate(args)
        elif args.phase == "write-checklist":
            result = write_checklist(args, args.runs_dir)
        elif args.phase == "test":
            result = run_test(args)
        elif args.phase == "aggregate":
            result = run_aggregate(args)
        else:
            result = {"status": "fail", "reason": f"unknown phase {args.phase}"}
    except Exception as e:  # noqa: BLE001
        result = {"status": "fail", "reason": f"unhandled exception: {e}", "traceback": traceback.format_exc()}

    if result.get("status") != "pass":
        print(json.dumps({k: v for k, v in result.items() if k != "traceback"}, indent=2), flush=True)
        if "traceback" in result:
            print(result["traceback"], flush=True)
    return 0 if result.get("status") == "pass" else 1


if __name__ == "__main__":
    sys.exit(main())
